version: '3'

services:

  mysql-db:
    image: mysql
    restart: unless-stopped
    volumes:
        - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: matt
      MYSQL_ROOT_user: matt
      MYSQL_ROOT_PASSWORD: matt
      MYSQL_USER: matt
      MYSQL_PASSWORD: matt
    ports:
      - "3306:3306"

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  meilisearch:
    image: getmeili/meilisearch:v0.29
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterkey"
    volumes:
      - ./meili_data:/meili_data


volumes:
    db_data: {}