version: '3'

services:
  app:
    build:
      args:
        user: matt
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: scotchegg-app-img:latest
    container_name: scotchegg-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network
  mysql-db:
    image: mysql
    restart: unless-stopped
    volumes:
        - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_user: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

    networks:
      - laravel-network

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  meilisearch:
    image: getmeili/meilisearch:v0.29
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterkey"
    volumes:
      - ./meili_data:/meili_data


volumes:
    db_data: {}

networks:
  laravel-network:
    driver: bridge